[0m06:16:33.878622 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80cf90b220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80ce8af7f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80ce8af790>]}


============================== 06:16:33.883264 | 8d2132c9-d388-4e54-a949-e0c6dbc1b71d ==============================
[0m06:16:33.883264 [info ] [MainThread]: Running with dbt=1.9.4
[0m06:16:33.883865 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/home/jaime/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run --select stg_cidades_sustentaveis', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m06:16:33.884478 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/jaime/observatudo-bq/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m06:16:33.888039 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.070001304, "process_in_blocks": "31312", "process_kernel_time": 0.115955, "process_mem_max_rss": "91408", "process_out_blocks": "8", "process_user_time": 1.381806}
[0m06:16:33.889817 [debug] [MainThread]: Command `dbt run` failed at 06:16:33.889682 after 0.07 seconds
[0m06:16:33.890214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80cf90b220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80ce8afeb0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f80ce8af7f0>]}
[0m06:16:33.890698 [debug] [MainThread]: Flushing usage events
[0m06:16:34.677109 [debug] [MainThread]: An error was encountered while trying to flush usage events
